apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.properties: |
    server.port={{ .Values.config.serverPort }}
    spring.application.name={{ .Chart.Name }}
    
    # Database
    spring.datasource.url={{ .Values.config.database.url }}
    spring.datasource.driver-class-name={{ .Values.config.database.driver }}
    spring.datasource.username={{ .Values.config.database.username }}
    spring.datasource.password={{ .Values.config.database.password }}
    
    # JPA
    spring.jpa.hibernate.ddl-auto={{ .Values.config.jpa.ddlAuto }}
    spring.jpa.show-sql={{ .Values.config.jpa.showSql }}
    
    # Logging
    logging.level.com.bank.account={{ .Values.config.logging.level }}

    # Zipkin
    management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    management.tracing.sampling.probability=1
    
    management.observations.enabled=true
    management.tracing.enabled=true
    spring.datasource.tracing.enabled=true
    management.metrics.enable.jdbc=true

    spring.kafka.producer.observation-enabled=true
    spring.kafka.consumer.observation-enabled=true
    spring.kafka.listener.observation-enabled=true