apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.image }}
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_CLUSTER_ID
          value: {{ .Values.clusterId }}
        - name: SERVICE_NAME
          value: "{{ .Chart.Name }}"  
        volumeMounts:
        - name: data
          mountPath: /kafka/data
        command:
        - "sh"
        - "-c"
        - |

          cat > /tmp/my-kafka-conf.properties << EOF
          node.id=0
          process.roles=broker,controller
          listeners=PLAINTEXT://:9092,CONTROLLER://:9093
          listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          controller.quorum.voters=0@localhost:9093
          controller.listener.names=CONTROLLER
          log.dirs=/kafka/data
          num.partitions=1
          offsets.topic.replication.factor=1
          transaction.state.log.replication.factor=1
          EOF
          echo "advertised.listeners=PLAINTEXT://${HOSTNAME}.kafka-headless:9092" >> /tmp/my-kafka-conf.properties

          /opt/kafka/bin/kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c /tmp/my-kafka-conf.properties --ignore-formatted

          /opt/kafka/bin/kafka-server-start.sh /tmp/my-kafka-conf.properties

  volumeClaimTemplates:  
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storageSize | default "1Gi" }}
