apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-services
  namespace: default
spec:
  selector: {}
#  selector:
#    matchLabels:
#      app.kubernetes.io/managed-by: Helm
  endpoints:
  - port: http
    path: /actuator/prometheus
    port: "8080" 
    interval: 15s