apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-services
  namespace: default
  labels:
    release: prometheus
spec:
  selector: {}
#  selector:
#    matchLabels:
#      app.kubernetes.io/managed-by: Helm
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
    relabelings:
    - source_labels: [__meta_kubernetes_service_name]
      target_label: service
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: pod

