apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-services
  namespace: default
  labels:
    release: prometheus
spec:
  selector: {}
#  selector:
#    matchLabels:
#      app.kubernetes.io/managed-by: Helm
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
