apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-services
  namespace: default
  labels:
    release: prometheus
spec:
  selector: {}
#  selector:
#    matchLabels:
#      app.kubernetes.io/managed-by: Helm
  endpoints:
  - port: 8080
    path: /actuator/prometheus
    interval: 15s


