image: "elasticsearch"
imageTag: "8.11.0"
imagePullPolicy: "Never"

replicas: 1

esConfig:
  elasticsearch.yml: |
    discovery.type: single-node

esJavaOpts: "-Xms512m -Xmx512m"

readinessProbe:
  enabled: false
livenessProbe:
  enabled: false

