image: "elasticsearch"
imageTag: "8.11.0"
imagePullPolicy: "Never"

replicas: 1

esConfig:
  elasticsearch.yml: |
    discovery.type: single-node

esJavaOpts: "-Xms512m -Xmx512m"

readinessProbe:
  enabled: false
livenessProbe:
  enabled: false

extraEnvs:
  - name: discovery.type
    value: single-node
  - name: discovery.seed_hosts 
    value: ""
  - name: cluster.initial_master_nodes
    value: ""
  - name: xpack.security.enabled
    value: "false"
  - name: xpack.security.transport.ssl.enabled
    value: "false"