image: logstash
imageTag: 9.1.7
imagePullPolicy: Never

replicas: 1

logstashPipeline:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["logs"]
        codec => "plain"
        group_id => "logstash"
        auto_offset_reset => "earliest"
      }
    }
    
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{GREEDYDATA:log_message}" }
      }
      
      mutate {
        add_field => { 
          "service" => "accounts"
          "environment" => "production" 
        }
      }
    }
    
    output {
      stdout { 
        codec => rubydebug 
      }
    }


