apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.properties: |
    server.port={{ .Values.config.serverPort }}
    spring.application.name={{ .Chart.Name }}
    
    # Database
    spring.datasource.url={{ .Values.config.database.url }}
    spring.datasource.driver-class-name={{ .Values.config.database.driver }}
    spring.datasource.username={{ .Values.config.database.username }}
    spring.datasource.password={{ .Values.config.database.password }}
    
    # JPA
    spring.jpa.hibernate.ddl-auto={{ .Values.config.jpa.ddlAuto }}
    spring.jpa.show-sql={{ .Values.config.jpa.showSql }}
    
    # Logging
    logging.level.com.bank.account={{ .Values.config.logging.level }}

    # Kafka Configuration
    spring.kafka.bootstrap-servers=kafka:9092
    spring.kafka.consumer.group-id=notify
    spring.kafka.consumer.auto-offset-reset=earliest
    #spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
    #spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

    # JSON сериализация
    spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
    spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
    spring.kafka.consumer.properties.spring.json.trusted.packages=*
    spring.kafka.consumer.properties.spring.json.use.type.headers=false
